website/views.py
import os
from mimetypes import guess_extension
import speech_recognition as sr
from flask_socketio import emit, join_room, leave_room
from flask import Blueprint, Response, render_template, request, url_for, jsonify, session, make_response, flash
from flask_login import login_required, current_user
from werkzeug.utils import redirect
from website import socketio
from .models import User
from text_to_asl import getVideoPath
from camera import Camera
from detection import wordsModel
from alphabet import letterModel
from . import db
import random, string

views = Blueprint('views', __name__)

model_words = wordsModel()
model_letters = letterModel()

# Variables for Chat Rooms
_users_in_room = {}
_room_of_sid = {}
_name_of_sid = {}

# Camera dictionary
cameras = {}


# ------ Routes and Sockets for From ASL -------- #
@socketio.on('connect', namespace='/from_asl')
def connect_camera():
    if session['username'] not in cameras:
        cameras[session['username']] = Camera(model_words, model_letters)
        print("camera created")
    print("client connected")

@socketio.on('input image', namespace='/from_asl')
def queue_image(input):
    # split input string
    input = input.split(",")[1]
    cameras[session['username']].enqueue_input(input)

@views.route('/clear_list', methods=['POST'])
@login_required
def clear_list():
    cameras[session['username']].wordList.clear()
    return ("nothing")

@views.route('/restart', methods=['POST'])
@login_required
def restart():
    cameras[session['username']].restartModel()

    return ("nothing")

@views.route ('/update_model', methods=['POST'])
@login_required
def update_model():
    model = request.form["value"]
    if model == "words":
        cameras[session['username']].updateModel(0)
    else:
        cameras[session['username']].updateModel(1)
    return("nothing")

@views.route('/get_words', methods=['POST', 'GET'])
def get_words():
    wordList = cameras[session['username']].wordList
    # this should return a jsonified format of the words in the class myWords.words list
    return jsonify({'results':wordList})

def generateVideo(username):
    # function to generate video stream from queue of output images
    while True:
        frame = cameras[username].get_frame()
        # frame = frame.tobytes()
        yield (b'--frame\r\n'b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


@views.route('/video_feed')
@login_required
def video_feed():
    #Video streaming route. Put this in the src attribute of an img tag
    return Response(generateVideo(session['username']), mimetype='multipart/x-mixed-replace; boundary=frame')

@views.route('/translate/fromASL', methods=['POST', 'GET'])
@login_required
def fromASL():
    session['username'] = current_user.username
    if session['username'] not in cameras:
        cameras[session['username']] = Camera(model_words, model_letters)
        print("camera created")
    return render_template("from_asl.html")

@views.route('/translate/toASL', methods=['POST', 'GET'])
@login_required
def toASL():
    if request.method == 'POST':
        data = request.form.get('text')
        json = getVideoPath(data)

        print("json ", json)
        return json
    else:
        return render_template("to_asl.html")

@views.route('/translate/audio', methods=['POST', 'GET'])
@login_required
def audioToText():
    print("reached audio to text page")
    return render_template("audio.html")

@views.route('/audiorecog', methods=['POST', 'GET'])
@login_required
def audiorecog():
    print('reached upload audio')
    if 'audio_file' in request.files:
        file = request.files['audio_file']
        if file:
            recognizer = sr.Recognizer()
            audioFile = sr.AudioFile(file)

            with audioFile as source:
                data = recognizer.record(source)
            transcript = recognizer.recognize_google(data, key=None)
            return make_response(transcript, 200)

        return make_response('', 200)

@views.route('/', methods=['POST','GET'])
@login_required
def home():
    return render_template("index.html")

@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'POST':
        data = request.form
        print(data)

        if ('userName' in data) and (data['userName'] != ''):
            new_username = data['userName']
            current_user.update_username(new_username)
            db.session.commit()

        if 'currPass' in data:
            curr_pass = data['currPass']
            new_pass1 = data['newPass1']
            new_pass2 = data['newPass2']
            if curr_pass != '':
                if current_user.check_password(curr_pass):
                    if new_pass1 == new_pass2:
                        if len(new_pass1) < 6:
                            flash('Password must be at least 6 characters long', 'error')
                        current_user.set_password(new_pass2)
                        db.session.commit()
                    else:
                        flash('Passwords do not match - please try again', 'error')
                else:
                    flash('Current password incorrect', 'error')

    return render_template("profile.html")

@views.route('/phrases')
@login_required
def phrases():
    return render_template("phrases.html")

@views.route('/about')
def about():
    return render_template("about.html")

@views.route('/help')
def help():
    return render_template("help.html")

@views.route('/list')
@login_required
def list():
    return render_template('profile_list.html', users=User.query.all(), title='Profiles List')

## -------------------------------------------- CONNECT/CHAT FUNCTIONS -------------------------------------------------

@views.route('/connect', methods=['GET', 'POST'])
@login_required
def chat_connect():
    if request.method == "POST":
        room_id = request.form['room_id']
        return redirect(url_for("views.waiting_room", room_id=room_id))

    return render_template("connect.html")

@views.route('/room/<string:room_id>/waitingroom', methods=['GET', 'POST'])
def waiting_room(room_id):

    if request.method == 'POST':
        display_name = request.form['display_name']
        # mute_audio = request.form['mute_audio']
        # mute_video = request.form['mute_video']
        session['chat'] = {"name": display_name, "room_id": room_id}#"mute_audio": mute_audio, "mute_video": mute_video}
        return redirect(url_for("views.enter_room", room_id=room_id))

    return render_template("chat_waitingroom.html", room_id=room_id)


@views.route('/room/<string:room_id>')
@login_required
def enter_room(room_id):
    session['username'] = current_user.username
    if 'chat' not in session:
        return redirect(url_for("views.waiting_room", room_id=room_id))

    if current_user.user_impairment == 2: # deaf user
        if session['username'] not in cameras: # if user camera does not exist, create
            cameras[session['username']] = Camera(model_words, model_letters)
        return render_template("from_asl_chat.html", room_id=room_id, display_name=session['chat']["name"])
    else:
        return render_template("to_asl_chat.html", room_id=room_id, display_name=session['chat']["name"])

    # return render_template("chatroom.html", room_id=room_id, display_name=session[room_id]["name"],
    #                        mute_audio=session[room_id]["mute_audio"], mute_video=session[room_id]["mute_video"])


@socketio.on('input image', namespace='/chat')
def queue_image(input):
    # split input string
    input = input.split(",")[1]

    cameras[session['username']].enqueue_input(input)

@socketio.on("join-room", namespace='/chat')
def join(message):
    room = session['chat']["room_id"]

    sid = request.sid
    join_room(room)
    emit('get-sid', {'sid': sid})
    emit('status', {'msg': '(' + session['chat']["name"] +' has entered the room)\n', 'sid': sid}, room=room)

@socketio.on("input-message", namespace='/chat')
def text(message):
    room = session['chat']["room_id"]
    sid = request.sid
    message = message['msg']
    emit('output-message', {'msg': session['chat']["name"] + ': ' + message + '\n', 'sid': sid}, room=room)

@socketio.on("leave-room", namespace='/chat')
def left(message):
    room = session['chat']["room_id"]
    emit('status', {'msg': '(' + session['chat']["name"] + ' has left the room)\n'}, room=room)
    leave_room(room)
    session['chat'] = None


# ----- for WEBRTC CONNECT CHAT -----

@socketio.on("connect", namespace='/chat')
def on_connect():

    sid = request.sid
    print("New Socket Connected", sid)

@socketio.on("join-room")
def on_join_room(data):

    sid = request.sid
    room_id = data["room_id"]
    display_name = session[room_id]["name"]

    # Register SID to the Room
    join_room(room_id)
    _room_of_sid[sid] = room_id
    _name_of_sid[sid] = display_name

    # Broadcast to Others in the Room
    print("[{}] New Member Joined: {}<{}>".format(room_id, display_name, sid))
    emit("user-connect", {"sid": sid, "name": display_name}, broadcast=True, include_self=False, room=room_id)

    # Add to User List Maintained on Server
    if room_id not in _users_in_room:
        _users_in_room[room_id] = [sid]
        emit("user-list", {"my_id": sid})
    else:
        usrlist = {u_id:_name_of_sid[u_id] for u_id in _users_in_room[room_id]}
        emit("user-list", {"list": usrlist, "my_id": sid})                          # Send List of Existing Users to the New Member
        _users_in_room[room_id].append(sid)                                         # Add New Member to User List Maintained on Server

    print("\nUsers: ", _users_in_room, "\n")

@socketio.on("disconnect")
def on_disconnect():

    sid = request.sid
    room_id = _room_of_sid[sid]
    display_name = _name_of_sid[sid]

    print("[{}] Member Left: {}<{}>".format(room_id, display_name, sid))
    emit("user-disconnect", {"sid": sid}, broadcast=True, include_self=False, room=room_id)

website/templates/about.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title%}About{% endblock %}

{% block content %}
<div class="text-center mt-5">
    <img src="static/audibleON_logo.png" width="150">
    <h4>About AudibleON</h4>
    <p>
        Audible ON, is a program, which is designed to auto detect gestures in American Sign Language (ASL) in order to enhance communication 
        abilities for users that may have a need for non-verbal communication in their daily life. Non-verbal communication is an imperative part 
        of life for those living with a hearing disability whether the impairment is mild or profound. Additionally, non-verbal communication 
        has become widely popular in the use of technology for user convenience. Considering this, this proposed application seeks to detect 
        and recognize ASL hand gestures for the purpose of communication. By utilizing computer vision and machine learning, a gesture can be 
        acknowledged and understood, resulting in either written, visual, or audible communication.
    </p>
    <p>Created by Cooper, Westburg, Lazzaro, Ahmed, Mercado, and Laubert (2022)</p>
</div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, intial-scale=1.0"/>

        <!-- Load Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"
        />

        <!-- Load Google Material Icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!-- Load SocketIO -->
        <script src="https://cdn.socket.io/4.4.1/socket.io.min.js" integrity="sha384-fKnu0iswBIqkjxrhQCTZ7qlLHOFEgNkRmK2vaO/LbTZSXdJfAu6ewRBdwHPhBo/H" crossorigin="anonymous"></script>

        <!-- video.js base CSS -->
        <link href="https://vjs.zencdn.net/7.18.1/video-js.css" rel="stylesheet" />

        <style>
            ::-moz-selection { /* Code for Firefox */
                color: white;
                background: #f2c738;
            }

            ::selection {
              color: white;
              background: #f2c738;
            }

            {% block style %}
            {% endblock %}
        </style>

        <title>{% block title %}Home{% endblock %}</title>
        
    </head>
    <body>
        {% block body %}

        <nav class="navbar navbar-expand lg navbar-light" style="background-color: #f2c738;">
            <button class ="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon" ></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-item nav-link" id="home" href="/">Translate</a>
                    </li>

                    {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="/" id="AccountDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="AccountDropDown">
                            <li><a class="nav-item nav-link" id="profile" href="/profile">Profile</a></li>
<!--                            <li><a class="nav-item nav-link" id="phrases" href="/phrases">Saved Phrases</a></li>-->
                            <li><a class="nav-item nav-link" id="logout" href="/logout">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    </li>
                    {% endif %}
                    
                    <li class="nav-item">
                        <a class="nav-item nav-link" id="about" href="/about">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" id="help" href="/help">Help</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith%}


        <div class="container">
            {% block content%}
            {% endblock %}
        </div>


        {% endblock %}

        <!-- jQuery JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <!-- Popper JS -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>

        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

        <!-- SocketIO -->
        <script src="https://cdn.socket.io/4.4.1/socket.io.min.js" integrity="sha384-fKnu0iswBIqkjxrhQCTZ7qlLHOFEgNkRmK2vaO/LbTZSXdJfAu6ewRBdwHPhBo/H" crossorigin="anonymous"></script>

        <!-- required scripts for video playlist building --->
        <script src="https://vjs.zencdn.net/7.18.1/video.min.js"></script>
        <script src="/static/videojs-playlist.min.js" type="text/javascript"></script>
        <script src="//cdn.sc.gl/videojs-hotkeys/0.2/videojs.hotkeys.min.js"></script>

        {% block script%}
        {% endblock %}

    </body>
</html>

website/templates/from_asl_chat.html
{% extends 'base.html' %}
{% block title %}Web Chat [{{ room_id }}]{% endblock %}
{% block style %}
    .btn {
        margin-top: 5px;
    }
    .col {
        width: 100%;
    }
     #videoStream {
         width: 240px;
         height: 180px;
        background-color: #666;
     }

     #imageElement {
         width: 240px;
         height: 180px;
         background-color: #666;
     }

     #canvasElement {
         width: 100%;
         height: 100%;
         display: none;
     }
    #scrollable{
        float: left;
        height: 180px;
        width: 100%;
        overflow-y: auto;
        white-space: pre-wrap;
    }
    #words{
        float: left;
        height: 180px;
        width: 100%;
    }
{% endblock %}

{% block content%}

<div class="heading mb-4">
    <h4>Web Chat - Room: <span class="heading-mark">{{room_id}}</span></h4>
    <h5>You have joined as <span id="display_name" class="heading-mark">{{display_name}}</span></h5>
</div>

<div class="container">
  <div class="row">
    <div class="col">
        Live Webcam<br>
        <video autoplay="false" id="videoStream"></video>
    </div>
    <div class="col">
        Processed Image<br>
        <img id="imageElement" src="{{ url_for('views.video_feed')}}">
        <canvas id="canvasElement"></canvas>

        <button type="button" id="restart" class="btn btn-danger">Restart</button>

        <input type="radio" class="btn-check" name="options-outlined" id="words-btn" value="words" autocomplete="off" checked>
        <label class="btn btn-outline-primary" for="words-btn" type="submit">Words</label>

        <input type="radio" class="btn-check" name="options-outlined" id="letters-btn" value="letters" autocomplete="off">
        <label class="btn btn-outline-primary" for="letters-btn" type="submit">Letters</label>
    </div>
    <div class="col-6">
      Video from Text
      <video id="videoPlayer" class="video-js vjs-default-skin vjs-big-play-centered" poster="static/audibleON_logo.png" autoplay controls width="240px" height="180px">
      </video>
    </div>
  </div>
  <div class="row">
      <div class="col">
        <h4>Translation Output</h4>
        <div id="words" class="rounded border border-dark"></div>
<!--        <textarea class="form-control" id="words" rows="6" disabled readonly></textarea>-->

        <button type="button" id="audio" class="btn btn-primary">Audio</button>
        <button type="button" id="clear" class="btn btn-primary">Clear</button>
        <button type="button" id="send" class="btn btn-success">Send Message</button>

      </div>
      <div class="col">
          <h4>Chat Log</h4>

          <div id='scrollable' class="rounded border border-dark" ></div>
          <button type="button" class="btn btn-primary" id='scroller'>Scroll to bottom!</button>
          <button class="btn btn-danger" type="submit" id='leave'>Leave</button>
      </div>
  </div>
</div>

{% endblock %}

{% block script %}

<script>
$(document).ready(function() {
    clearList();
    var formData = {
      'value': 'words'
    };
    console.log(formData);
    $.ajax({
          type: 'POST',
          url: "{{ url_for('views.update_model') }}",
          data: formData,
          dataType: 'json',
          encode: true
      })
      .done(function(data) {
          console.log(data);
      })
});

function getAudio(){
    var updatedText = $.get("{{ url_for('views.get_words') }}");

    updatedText.done(function(results) {
        var result = "";

        results.results.forEach(item => {
            item = item.replaceAll("_", " ");
            result = result.concat(" ", item);
        });

        console.log(result)
        var msg = new SpeechSynthesisUtterance('Translated output:'+result);
        window.speechSynthesis.speak(msg);
    });
}

$('.btn-check').click(function(){
        var formData = {
          'value': $(this).attr('value')
        };
        console.log(formData);
        $.ajax({
              type: 'POST',
              url: "{{ url_for('views.update_model') }}",
              data: formData,
              dataType: 'json',
              encode: true
          })
          .done(function(data) {
              console.log(data);
          })
    });

function clearList() {
    $.ajax({url: "{{ url_for('views.clear_list') }}", type: 'POST'})
        .done(function() {
      });
    updateText();
}


function restart() {
    $.ajax({url: "{{ url_for('views.restart') }}", type: 'POST'})
        .done(function() {
          console.log("restart pressed");
    });
}


function updateText(){
    var updatedText = $.get("{{ url_for('views.get_words') }}");
    var words = document.getElementById('words');
    let numb = document.getElementById("words").childNodes.length;

    updatedText.done(function(results) {
        var result = "";
        results.results.forEach(item => {
            item = item.replaceAll("_", " ");
            result = result.concat(" ", item);
        });

        var newText = document.createTextNode(result);

        if (numb === 0){
            words.appendChild(newText);
        } else {
            words.removeChild(words.lastChild);
            words.appendChild(newText);
        }
    });
}

function getVideoPlaylist(data){
    let formData = new FormData()
    formData.append('text', data)
    $.ajax({
        type: 'POST',
        url: "{{ url_for('views.toASL') }}",
        data: formData,
        cache: false,
        processData: false,
        contentType: false
    }).done(function(data){
        console.log(data)

        var videos = JSON.parse(data.replace(/&#34;/g,'"'));

        let resources = [];

        videos.forEach(video => {
            let vidName = video;
            console.log(vidName);
            let resource = {
                sources: [{
                    src: vidName,
                    type: 'video/mp4'
                }],
            }
            resources.push(resource)
        });
        var player = videojs('videoPlayer');
        player.playlist(resources);
        player.playlist.autoadvance(0);
        });
}
</script>
<script src="/static/fromASL_chat.js" type="text/javascript"></script>

{% endblock %}

website/templates/index.html
<!DOCTYPE html>
{% extends 'base_two.html' %}

{% block title%}Translate{% endblock %}

{% block style %}
    .btn-primary:hover {
        background-color: #3157d4;
        border-color: #3157d4;
    }
    .btn-primary {
        background-color: #3863f2;
        border-color: #3863f2;
        display: block;
        margin-left: auto;
        margin-right: auto;
        margin-top: 30px;
        margin-bottom: 10px;
        width: 300px;
        height: 100px;
        font-size: 175%;
    }

{% endblock %}

{% block content %}
<div class="d-grid gap-4 col-5 mx-auto d-md-block">
  <button class="btn btn-primary btn-lg" type="submit" onclick="location.href = '/translate/fromASL';">ASL to Text</button>
  <button class="btn btn-primary btn-lg" type="submit" onclick="location.href = '/translate/toASL';">Text to ASL</button>
  <button class="btn btn-primary btn-lg" type="submit" onclick="location.href = '/translate/audio';">Audio to ASL</button>
  <button class="btn btn-primary btn-lg" type="submit" onclick="location.href = '/connect';">Connect Online</button>
</div>

{% endblock %}

{% block script %}
{% endblock %}

website/templates/to_asl.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}Translate to ASL{% endblock %}

{% block style %}
    .row {
      padding-top: 20px;
    }
    .btn {
        margin-top: 5px;
    }
{% endblock %}

{% block content %}

<div class="container">
   <div class="row">
        <div class="d-flex justify-content-center ">
            <video id="videoPlayer" class="video-js vjs-default-skin vjs-big-play-centered"
                   poster="static/audibleON_logo.png" autoplay controls width="640px" height="360px"
                   preload="auto" playsinline="">
            </video>
        </div>
   </div>
    <div class="row">
        <div class="col text-center">
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="exampleModal" id="launchModal">
              Enter Text
            </button>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Text to ASL</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <div class="modal-body">
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Enter the text for translation to ASL below:</label>
            <textarea class="form-control" name="text" id="message-text"></textarea>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="submit_text">Translate</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block script %}
<script>
    $(document).ready(function(){
        $("#exampleModal").modal('show');
    });

   $('#launchModal').on('click', function (e) {
        $("#exampleModal").modal('show');
    });

   var textArea = document.getElementById('message-text')

   $('#submit_text').click(function (){
        message = textArea.value;
        console.log(message);
        textArea.value = '';
       $("#exampleModal").modal('hide');
        getVideoPlaylist(message);
    });

   function getVideoPlaylist(data){
    let formData = new FormData()
    formData.append('text', data)
    $.ajax({
        type: 'POST',
        url: "{{ url_for('views.toASL') }}",
        data: formData,
        cache: false,
        processData: false,
        contentType: false
    }).done(function(data){
        console.log(data)

        var videos = JSON.parse(data.replace(/&#34;/g,'"'));

        let resources = [];

        videos.forEach(video => {
            let vidName = video;

            // preload video source
            var preloadLink = document.createElement("link");
            preloadLink.href = vidName;
            preloadLink.rel = "preload";
            preloadLink.as = "video";
            preloadLink.type="video/mp4";
            document.head.appendChild(preloadLink);

            console.log(vidName);
            let resource = {
                sources: [{
                    src: vidName,
                    type: 'video/mp4'
                }],
            }
            resources.push(resource)
        });
        var player = videojs('videoPlayer');
        player.playlist(resources);
        player.playlist.autoadvance(0);
        });
    }

</script>
{% endblock %}

website/templates/to_asl_chat.html
{% extends 'base.html' %}
{% block title %}Web Chat [{{ room_id }}]{% endblock %}
{% block style %}
    .btn {
        margin-top: 5px;
    }
    .col {
        width: 100%;
    }
    #scrollable{
        float: left;
        height: 180px;
        width: 100%;
        overflow-y: auto;
        white-space: pre-wrap;
    }
    #audio_words{
        float: left;
        width: 100%;
    }
{% endblock %}

{% block content%}

<div class="heading mb-4">
    <h4>Web Chat - Room: <span class="heading-mark">{{room_id}}</span></h4>
    <h5>You have joined as <span class="heading-mark">{{display_name}}</span></h5>
</div>

<div class="container">
  <div class="row">
    <div class="col">
        <h4>Audio to Text</h4>
        <button class="btn btn-primary" id="recordButton" value="Start Recording">Start Recording</button>
        <button class="btn btn-danger" id="stopButton" value="Stop Recording" disabled>Stop Recording</button>
        <br><br>
        <audio id="audioPlay" controls></audio>
    </div>
    <div class="col">
          <h4>Chat Log</h4>

          <div id='scrollable' class="rounded border border-dark" ></div>
          <button type="button" class="btn btn-primary" id='scroller'>Scroll to bottom!</button>
          <button class="btn btn-danger" type="submit" id='leave'>Leave</button>
      </div>
  </div>
  <div class="row">
      <div class="col">
        <h4>Edit Text</h4>
        <textarea id="audio_words" class="form-control" rows="2"></textarea>
        <button id="audio_send" type="button" class="btn btn-success">Send Message</button>
      </div>
      <div class="col"></div>
  </div>
</div>

{% endblock %}


{% block script %}
<script>


$('#scroller').click(function (){
$('#scrollable').animate({ scrollTop: 		$('#scrollable').prop('scrollHeight')}, 1000);
});

URL = window.URL || window.webkitURL;
var gumStream, rec, input;

var AudioContext = window.AudioContext || window.webkitAudioContext;
var audioContext = new AudioContext;

var recordButton = document.getElementById("recordButton");
var stopButton = document.getElementById("stopButton");
var playAudio = document.getElementById('audioPlay');
var textArea = document.getElementById('audio_words')

recordButton.addEventListener("click", startRecording);
stopButton.addEventListener("click", stopRecording);

function startRecording() {
    console.log("recordButton clicked");

    var constraints = {
        audio: true,
        video: false
    }

    recordButton.disabled = true;
    stopButton.disabled = false;

    navigator.mediaDevices.getUserMedia(constraints).then(function(stream) {
        gumStream = stream;
        input = audioContext.createMediaStreamSource(stream);
        rec = new Recorder(input, {
            numChannels: 1
        })
        rec.record()
        console.log("Recording started");
    }).catch(function(err) {
        recordButton.disabled = false;
        stopButton.disabled = true;
    });
}

function stopRecording() {
    console.log("stopButton clicked");

    stopButton.disabled = true;
    recordButton.disabled = false;

    rec.stop();
    gumStream.getAudioTracks()[0].stop();

    rec.exportWAV(createDownloadLink);
}

function createDownloadLink(blob) {
    var url = URL.createObjectURL(blob);
    var au = document.createElement('audio');


    au.controls = true;
    au.src = url;
    playAudio.src = window.URL.createObjectURL(blob)

    let formData = new FormData();
    formData.append("audio_file", blob);

    $.ajax({
        type: 'POST',
        url: "{{ url_for('views.audiorecog') }}",
        data: formData,
        cache: false,
        processData: false,
        contentType: false
    }).done(function(data){
        console.log(data)
        textArea.value = data;
    });
}

</script>
<script src="https://cdn.rawgit.com/mattdiamond/Recorderjs/08e7abd9/dist/recorder.js"></script>
<script src="/static/recording.js"></script>
<script src="/static/toASL_chat.js" type="text/javascript"></script>

{% endblock %}